# This is a sample config file that does not have multiple solr instances. You will also need to be sure to
# edit the fedora.yml file to match the solr URL for active-fedora. 
development:
  url: <%= ENV.fetch('APPS_DHH_DEV_SOLR_URL') {'http://tomcat:8080/solr/blacklight'}%>
demo:
  url: <%= ENV.fetch('APPS_DHH_DEMO_SOLR_URL') {'http://localhost:8080/solr/blacklight'}%>
pontos:
  url: <%= ENV.fetch('APPS_DHH_PONTOS_SOLR_URL') {'http://localhost:8080/solr/blacklight'}%>
gimili:
  url: <%= ENV.fetch('APPS_DHH_GIMILI_SOLR_URL') {'http://localhost:8080/solr/blacklight'}%>
staging:
  url: <%= ENV.fetch('APPS_DHH_STAGING_SOLR_URL') {'http://localhost:8080/solr/blacklight'}%>
qa:
  url: <%= ENV.fetch('APPS_DHH_QA_SOLR_URL') {'http://localhost:8080/solr/blacklight'}%>
test: &TEST
  url: <%= ENV.fetch('APPS_DHH_TEST_SOLR_URL') {'http://localhost:8080/solr/blacklight'}%>
cucumber:
  <<: *TEST
production:
  url: <%= ENV.fetch('APPS_DHH_PROD_SOLR_URL') {'http://your.production.server:8080/bl_solr/core0'}%>
